### ISSUE TITLE
 Request: change branch master to main

### ISSUE THREAD

**Issue by robjloranger** [VivumLab/VivumLab#122]

**Comment by voryzen** [comment]
Hi Rob,
Why would you like to see the master branch, changed to main?

**Comment by robjloranger** [comment]
The master-slave terms carry implications/connotations of racial supremacy and oppression.

I think it doesn't belong in software development and can make the project more welcoming to a larger group of people. Everyone should be comfortable.

**Comment by voryzen** [comment]
We will consider your views, Rob. Certainly, they are valid, and I'm glad you brought this up.

The beauty of the internet is, by far, the unity of people regardless of racial or geographical bounds; developers are judged not on the colour of their skin, their spoken language, or their lifestyle choices, but on their ability to problem solve and write readable, auditable and (in ways) beautiful code.. as such, racism and racial supremacy holds no place here, and in reality, it has not for quite some time.

You need only look as far as the VivumLab statement to know that VivumLab is developed free of charge for the benefit of all that want to run this code, for their own benefit, and possibly (if they so wish) to be part of this community.
VivumLab only request one's time, one's patience and one's tolerance, towards others. I speak this, as a mixed race person, with a further diversified family of my own.

VivumLab is a means to an end (a way to protect one's data), not to make anyone feel uncomfortable. It is our hope that you will decide to create fantastic code with us, so that the next person can protect their own data, online.

If this situation should arise, and you are poised by another with this issue; you are most welcome to direct them to this comment, and invite them to join us in making the world a better place.. one piece of code at a time.

**Comment by denis-ev** [comment]
@robjloranger @voryzen 
I see your points, but I don't think we should change it! 
Changing means modifying support systems like travis to not use the default set everywhere.

This is a quote from [wikipedia](https://en.wikipedia.org/wiki/Master/slave_(technology)), with which I totally agree and don't see a point of changing master. 

>  Many developers in the discussion on whether to make the replacement agreed that the term "slave" should be replaced while "master" was not offensive, while others argued that changing "slave" was also unnecessary.

Sorry, but changing the everywhere default `master` to something else, just creates more problems.
